[package]
name = "raptor-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.bnum]
version = "0.11.0"
default-features = false

[dependencies.gtfs-structures]
version = "0.41.2"
default-features = false
features = []
