[package]
name = "raptor-rs"
version = "0.1.0"
edition = "2021"

# Open Street Map import osm4routing2

[dependencies]
chrono = { version = "0.4.37", default-features = false }

[dependencies.bnum]
version = "0.11.0"
default-features = false

[dependencies.gtfs-structures]
version = "0.41.2"
default-features = false
features = []
