[package]
name = "dev_utils"
version = "0.1.0"
edition = "2021"

[lib]
name = "dev_utils"
path = "src/lib.rs"

[dependencies]
chrono = "0.4.38"
gtfs-structures =  { version = "0.41", default-features = false }
raptor-rs = { path = ".." }